pipeline {
    agent any

environment {
    DOTNET_HOME = "C:\\Program Files\\dotnet"
}



    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/emailtovijay-tech/Selenium-Webdriver.git', branch: 'master'
            }
        }

        stage('Restore Dependencies') {
            steps {
                bat "${DOTNET_HOME}\\dotnet restore Selenium-Webdriver\\Selenium-Webdriver.csproj"
            }
        }

        stage('Build') {
            steps {
                bat "${DOTNET_HOME}\\dotnet build Selenium-Webdriver\\Selenium-Webdriver.csproj --configuration Release"
            }
        }

        stage('Run Tests') {
            steps {
                // Run NUnit tests and generate TRX results
                bat "${DOTNET_HOME}\\dotnet test Selenium-Webdriver\\Selenium-Webdriver.csproj --configuration Release --logger \"trx;LogFileName=TestResults\\result.trx\""
                
                // Convert TRX to JUnit XML for Jenkins
                bat "${DOTNET_HOME}\\dotnet tool install --global trx2junit || echo Already installed"
                bat "trx2junit Selenium-Webdriver\\TestResults\\result.trx"
            }
        }

        stage('Publish Test Results') {
            steps {
                // Jenkins reads the JUnit XML generated by trx2junit
                junit 'Selenium-Webdriver\\TestResults\\*.xml'
            }
        }

        stage('Archive Build') {
            steps {
                archiveArtifacts artifacts: 'Selenium-Webdriver\\bin\\Release\\**\\*.*', allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            echo 'Cleaning up workspace...'
            cleanWs()
        }
        failure {
            echo 'Build failed!'
        }
        success {
            echo 'Build and tests succeeded!'
        }
    }
}
